const letterPositions = {
  e: [
    { x: 0, y: 0 },
    { x: 1, y: 0 },
    { x: 2, y: 0 },
    { x: 3, y: 0 },
    { x: 0, y: 1 },
    { x: 0, y: 2 },
    { x: 1, y: 2 },
    { x: 1, y: 1 },
    { x: 2, y: 1 },
    { x: 3, y: 1 },
    { x: 0, y: 3 },
    { x: 1, y: 3 },
    { x: 0, y: 4 },
    { x: 1, y: 4 },
    { x: 2, y: 3 },
    { x: 3, y: 3 },
    { x: 2, y: 4 },
    { x: 3, y: 4 },
    { x: 0, y: 5 },
    { x: 1, y: 5 },
    { x: 0, y: 6 },
    { x: 1, y: 6 },
    { x: 2, y: 6 },
    { x: 0, y: 7 },
    { x: 1, y: 7 },
    { x: 2, y: 7 },
    { x: 3, y: 7 },
    { x: 3, y: 6 },
    { x: 4, y: 0 },
    { x: 4, y: 1 },
    { x: 4, y: 3 },
    { x: 4, y: 4 },
    { x: 4, y: 6 },
    { x: 4, y: 7 },
  ],
  i: [
    { x: 0, y: 0 },
    { x: 1, y: 0 },
    { x: 0, y: 1 },
    { x: 1, y: 1 },
    { x: 0, y: 3 },
    { x: 1, y: 3 },
    { x: 0, y: 4 },
    { x: 1, y: 4 },
    { x: 0, y: 5 },
    { x: 1, y: 5 },
    { x: 0, y: 6 },
    { x: 1, y: 6 },
    { x: 0, y: 7 },
    { x: 1, y: 7 },
  ],
  d: [
    { x: 0, y: 6 },
    { x: 0, y: 5 },
    { x: 0, y: 4 },
    { x: 1, y: 4 },
    { x: 1, y: 5 },
    { x: 1, y: 7 },
    { x: 1, y: 6 },
    { x: 1, y: 3 },
    { x: 2, y: 3 },
    { x: 3, y: 3 },
    { x: 3, y: 4 },
    { x: 2, y: 4 },
    { x: 2, y: 7 },
    { x: 2, y: 6 },
    { x: 3, y: 6 },
    { x: 3, y: 7 },
    { x: 4, y: 7 },
    { x: 4, y: 6 },
    { x: 4, y: 5 },
    { x: 4, y: 4 },
    { x: 4, y: 3 },
    { x: 4, y: 2 },
    { x: 4, y: 1 },
    { x: 4, y: 0 },
    { x: 5, y: 0 },
    { x: 5, y: 1 },
    { x: 5, y: 2 },
    { x: 5, y: 3 },
    { x: 5, y: 4 },
    { x: 5, y: 5 },
    { x: 5, y: 6 },
    { x: 5, y: 7 },
  ],
  r: [
    { x: 2, y: 0 },
    { x: 1, y: 1 },
    { x: 2, y: 1 },
    { x: 1, y: 2 },
    { x: 2, y: 2 },
    { x: 1, y: 3 },
    { x: 2, y: 3 },
    { x: 1, y: 4 },
    { x: 2, y: 4 },
    { x: 3, y: 1 },
    { x: 4, y: 0 },
    { x: 4, y: 0 },
    { x: 4, y: 1 },
    { x: 4, y: 1 },
    { x: 3, y: 0 },
  ],
  a: [
    { x: 0, y: 1 },
    { x: 1, y: 0 },
    { x: 1, y: 1 },
    { x: 1, y: 2 },
    { x: 0, y: 2 },
    { x: 0, y: 3 },
    { x: 1, y: 3 },
    { x: 1, y: 4 },
    { x: 2, y: 0 },
    { x: 3, y: 0 },
    { x: 3, y: 1 },
    { x: 2, y: 1 },
    { x: 4, y: 0 },
    { x: 4, y: 1 },
    { x: 2, y: 4 },
    { x: 3, y: 4 },
    { x: 4, y: 4 },
    { x: 4, y: 3 },
    { x: 3, y: 3 },
    { x: 2, y: 3 },
    { x: 5, y: 4 },
    { x: 5, y: 3 },
    { x: 5, y: 2 },
    { x: 5, y: 1 },
    { x: 5, y: 3 },
    { x: 4, y: 2 },
    { x: 5, y: 0 },
    { x: 5, y: -1 },
    { x: 4, y: -1 },
  ],
};

const eidraLogo = {
  E: {
    offset: { x: 0, y: 0 },
    positions: letterPositions.e,
  },
  I: {
    offset: { x: 6, y: 0 },
    positions: letterPositions.i,
  },
  D: {
    offset: { x: 9, y: 0 },
    positions: letterPositions.d,
  },
  R: {
    offset: { x: 15, y: 3 },
    positions: letterPositions.r,
  },
  A: {
    offset: { x: 21, y: 3 },
    positions: letterPositions.a,
  },
};

const ObstacleUtils = {
  addEidraLogo: () => {
    state.grid.blackCells = [];

    for (let letter in eidraLogo) {
      eidraLogo[letter].positions.forEach((position) => {
        const x =
          state.eidraLogo.position.x + position.x + eidraLogo[letter].offset.x;
        const y =
          state.eidraLogo.position.y + position.y + eidraLogo[letter].offset.y;
        CellUtils.draw(x, y);
      });
    }
  },
};
